export const AbstractContextContainer: typeof AbstractContextContainerModule;
export const ContextContainer: typeof ContextContainerModule;
export const ContextContainerFactory: typeof ContextContainerFactoryModule;
export const AbstractContextContainerFactory: typeof AbstractContextContainerFactoryModule;
export const DemandedConfig: typeof DemandedConfigModule;
export const SessionConfig: typeof SessionConfigModule;
export const SingletoneConfig: typeof SingletoneConfigModule;
export const DIObjectConfig: typeof DIObjectConfigModule;
export const DIClazz: typeof DIClazzModule;
export const DIObjectKey: typeof DIObjectKeyModule;
export const SingletoneContainer: typeof SingletoneContainerModule;
export const SimpleContainer: typeof SimpleContainerModule;
export const DemandedFactory: typeof DemandedFactoryModule;
export const SessionContainer: typeof SessionContainerModule;
export const DemandedLifecycle: typeof DemandedLifecycleModule;
export const SingletoneLifecycle: typeof SingletoneLifecycleModule;
export const SessionLifecycle: typeof SessionLifecycleModule;
export const Lifecycle: typeof LifecycleModule;
export default Dizy;
import AbstractContextContainerModule from "./containers/AbstractContextContainer.js";
import ContextContainerModule from "./containers/ContextContainer.js";
import ContextContainerFactoryModule from "./containers/ContextContainerFactory.js";
import AbstractContextContainerFactoryModule from "./containers/AbstractContextContainerFactory.js";
import { DemandedConfig as DemandedConfigModule } from "./DIObjectConfig.js";
import { SessionConfig as SessionConfigModule } from "./DIObjectConfig.js";
import { SingletoneConfig as SingletoneConfigModule } from "./DIObjectConfig.js";
import { DIObjectConfig as DIObjectConfigModule } from "./DIObjectConfig.js";
import DIClazzModule from "./DIClazz.js";
import DIObjectKeyModule from "./containers/helpers/DIObjectKey.js";
import SingletoneContainerModule from "./containers/SingletoneContainer.js";
import SimpleContainerModule from "./containers/SimpleContainer.js";
import DemandedFactoryModule from "./containers/DemandedFactory.js";
import SessionContainerModule from "./containers/SessionContainer.js";
import DemandedLifecycleModule from "./lifecycle/DemandedLifecycle.js";
import SingletoneLifecycleModule from "./lifecycle/SingletoneLifecycle.js";
import SessionLifecycleModule from "./lifecycle/SessionLifecycle.js";
import LifecycleModule from "./lifecycle/Lifecycle.js";
declare namespace Dizy {
    export { ContextContainerModule as ContextContainer };
    export { AbstractContextContainerModule as AbstractContextContainer };
    export { DemandedFactoryModule as DemandedFactory };
    export { SimpleContainerModule as SimpleContainer };
    export { SessionContainerModule as SessionContainer };
    export { SingletoneContainerModule as SingletoneContainer };
    export { DIObjectKeyModule as DIObjectKey };
    export { DemandedConfigModule as DemandedConfig };
    export { SessionConfigModule as SessionConfig };
    export { SingletoneConfigModule as SingletoneConfig };
    export { DIObjectConfigModule as DIObjectConfig };
    export { DIClazzModule as DIClazz };
    export { DemandedLifecycleModule as DemandedLifecycle };
    export { SingletoneLifecycleModule as SingletoneLifecycle };
    export { SessionLifecycleModule as SessionLifecycle };
    export { LifecycleModule as Lifecycle };
    export { ContextContainerFactoryModule as ContextContainerFactory };
    export { AbstractContextContainerFactoryModule as AbstractContextContainerFactory };
}
